# Generated by Django 6.0.6 on 2026-07-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('paragraphs', models.JSONField(default=list)),
                ('views', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NameTrendStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('hanja', models.CharField(blank=True, max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('delta', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'gender', 'rank'],
                'indexes': [models.Index(fields=['year', 'gender'], name='naming_name_year_cba297_idx')],
            },
        ),
    ]
