# Generated by Django 6.0.6 on 2026-07-08 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_consent_into_profile(apps, schema_editor):
    """UserConsent(약관 동의 전용 모델, daesung 브랜치에서 UserProfile로 통합됨)에
    남아있던 기존 가입자 동의 기록을 새 UserProfile로 옮긴다. UserConsent 삭제 전에만
    실행 가능하므로 DeleteModel 직전에 배치한다."""
    UserConsent = apps.get_model("naming", "UserConsent")
    UserProfile = apps.get_model("naming", "UserProfile")
    for consent in UserConsent.objects.all():
        UserProfile.objects.update_or_create(
            user_id=consent.user_id,
            defaults={
                "terms_version": consent.terms_version,
                "privacy_version": consent.privacy_version,
                "terms_agreed_at": consent.terms_agreed_at,
                "privacy_agreed_at": consent.privacy_agreed_at,
                "agreed_ip": consent.agreed_ip,
                "user_agent": consent.user_agent,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0002_userconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('signups', models.PositiveIntegerField(default=0)),
                ('logins', models.PositiveIntegerField(default=0)),
                ('naming_requests', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('answered_inquiries', models.PositiveIntegerField(default=0)),
                ('source_distribution', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrendArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('paragraphs', models.JSONField(default=list)),
                ('views', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('VIEW_PII', 'PII 상세 조회'), ('ROLE_CHANGE', '권한 변경'), ('USER_UPDATE', '회원 수정'), ('USER_DELETE', '회원 삭제'), ('APPROVE', '가입 승인/거절'), ('CONTENT', '콘텐츠 변경'), ('LOGIN', '관리자 로그인'), ('OTHER', '기타')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', '최고관리자'), ('ADMIN', '운영관리자'), ('ANALYST', '분석/읽기전용')], default='ADMIN', max_length=20)),
                ('display_name', models.CharField(max_length=50)),
                ('is_active_admin', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('received', '접수'), ('in_progress', '처리 중'), ('answered', '답변 완료')], default='received', max_length=20)),
                ('admin_reply', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NameTrendStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('hanja', models.CharField(blank=True, max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('delta', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'gender', 'rank'],
                'indexes': [models.Index(fields=['year', 'gender'], name='naming_name_year_cba297_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', '임시'), ('SCHEDULED', '예약'), ('PUBLISHED', '게시'), ('ENDED', '종료')], default='DRAFT', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'naming_setting',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('SUSPENDED', '정지')], default='ACTIVE', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인'), ('REJECTED', '거절')], default='APPROVED', max_length=20)),
                ('rejected_reason', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('privacy_version', models.CharField(default='1.0', max_length=20)),
                ('terms_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(backfill_consent_into_profile, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='UserConsent',
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action', 'created_at'], name='naming_admi_action_1a9f35_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='naming_admi_actor_i_a54f27_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'created_at'], name='naming_logi_user_id_bd76ef_idx'),
        ),
    ]
