# Generated by Django
from django.db import migrations

def seed_sitetexts(apps, schema_editor):
    SiteTextSetting = apps.get_model('naming', 'SiteTextSetting')
    defaults = [
        {"key": "landing.title", "value": "프리미엄 작명소 명가"},
        {"key": "landing.subtitle", "value": "전통 사주명리학과 최신 AI 기술의 결합"},
        {"key": "policy.terms", "value": "이용약관 내용이 들어갑니다."},
        {"key": "policy.privacy", "value": "개인정보처리방침 내용이 들어갑니다."},
    ]
    for item in defaults:
        SiteTextSetting.objects.get_or_create(key=item["key"], defaults={"value": item["value"]})

class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0009_sitetextsetting'),
    ]

    operations = [
        migrations.RunPython(seed_sitetexts),
    ]
