# Generated by Django 6.0.6 on 2026-07-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0011_faqcategory_slug_activeusertracking_apiusagelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeusertracking',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
