# Generated by Django 6.0.6 on 2026-07-07 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0013_userconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceSetting',
            new_name='Setting',
        ),
        migrations.RemoveIndex(
            model_name='activeusertracking',
            name='naming_acti_last_se_287c24_idx',
        ),
        migrations.DeleteModel(
            name='ActiveUserTracking',
        ),
        migrations.RemoveIndex(
            model_name='apiusagelog',
            name='naming_apiu_created_f0a433_idx',
        ),
        migrations.DeleteModel(
            name='ApiUsageLog',
        ),
        migrations.DeleteModel(
            name='DailyMetric',
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='inquiryreplytemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inquiryreplytemplate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sitetextsetting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agreed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterModelTable(
            name='setting',
            table='naming_setting',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
        migrations.DeleteModel(
            name='InquiryReplyTemplate',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SiteTextSetting',
        ),
        migrations.DeleteModel(
            name='UserConsent',
        ),
    ]
