# Generated by Django 6.0.6 on 2026-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0015_dailymetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='original_email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('SUSPENDED', '정지')], default='ACTIVE', max_length=20),
        ),
    ]
